[package]
name = "atwinc1500"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { version = "0.2", features=["unproven"] }
embedded-nal = "0.6"
defmt = "0.3.0"
nb = "1.0.0"
